#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#80CBC4"
bspc config normal_border_color "#424242"
bspc config presel_feedback_color "#C792EA"

bspc rule -a firefox desktop='^3' follow=on focus=on
bspc rule -a Pavucontrol desktop='^5'

# Set wallpaper
nitrogen --restore &

# Start compositor
picom &

# Launch bar (polybar)
bash $HOME/.config/polybar/launch.sh &

wmname LG3D &
